version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    depends_on:
      - streamlit
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0